In [1]:
import numpy as np

## Agenda
1- Introduction to Numpy
2- Creating 1D Numpy Array
3- Creating 2D Numpy Array
4- Finding Dimensions of Array - shape
5- Finding Datatype of Array - dtype
6- Array Creation and Initialization Functions - Zeros
7- Array Creation and Initialization Functions - Ones
8- Array Creation and Initialization Functions - empty
9- Array Creation and Initialization Functions - eye
10- Array Creation and Initialization Functions - orange
11- Summarize

In [2]:
#Creating 1D Numpy Array

mylist1 = [101, 102, 103]
myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [3]:
#Creating 2D Numpy Array

mylist2 = [201, 202, 203]
myArray2D = np.array([mylist1, mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [4]:
#Finding Dimensions of Array - shape
print("myArray Dimension is")
print(myArray.shape)
print("myArray2D Dimension is")
print(myArray2D.shape)

myArray Dimensions
(3,)
myArray2D Dimenssions
(2, 3)


In [5]:
#Finding Datatype of Array - dtype
print("myArray Datatype")
print(myArray.dtype)
print("myArray2D Datatype")
print(myArray2D.dtype)

myArray Datatype
int32
myArray2D Datatype
int32


In [6]:
#Array Creation and Initialization Functions - Zeros 

zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [7]:
#Creating 1D Numpy Array

mylist1 = [10, 12, 13]
myArray = np.array(mylist1)

#Creating 2D Numpy Array
mylist2 = [21, 20, 33]
myArray2D = np.array([mylist1, mylist2])



#Printing the result
print('1D Numpy Array')
print(myArray)
print()
print('2D Numpy Array')
print(myArray2D)

1D Numpy Array
[10 12 13]

2D Numpy Array
[[10 12 13]
 [21 20 33]]
