In [1]:
import pandas as pd
import numpy as np

In [2]:
#what is Concatenation - Concatenation is the technique of combining two strings

In [3]:
#concatenation of Numpy Arrays
A1 = np.arange(25).reshape(5,5)
B1 = np.random.randn(25).reshape(5,5)

In [4]:
print(A1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
print(B1)

[[-0.46719037 -0.14593801  0.91247623 -2.1880976  -0.0178411 ]
 [ 0.04690297  0.49175207  2.10734754 -0.53696272  0.43452412]
 [ 0.91351235 -0.65627814 -1.31970248  0.04283077  0.02017721]
 [-0.34908829  0.94711594 -1.40815374  0.40506189 -1.67177413]
 [ 1.04828438  1.32936884 -1.51164245  0.3955147   0.0331612 ]]


In [6]:
np.concatenate([A1,B1], axis=1)

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00, -4.67190369e-01,
        -1.45938013e-01,  9.12476227e-01, -2.18809760e+00,
        -1.78411034e-02],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00,  4.69029684e-02,
         4.91752075e-01,  2.10734754e+00, -5.36962717e-01,
         4.34524116e-01],
       [ 1.00000000e+01,  1.10000000e+01,  1.20000000e+01,
         1.30000000e+01,  1.40000000e+01,  9.13512350e-01,
        -6.56278142e-01, -1.31970248e+00,  4.28307664e-02,
         2.01772145e-02],
       [ 1.50000000e+01,  1.60000000e+01,  1.70000000e+01,
         1.80000000e+01,  1.90000000e+01, -3.49088291e-01,
         9.47115940e-01, -1.40815374e+00,  4.05061887e-01,
        -1.67177413e+00],
       [ 2.00000000e+01,  2.10000000e+01,  2.20000000e+01,
         2.30000000e+01,  2.40000000e+01,  1.04828438e+00,
         1.32936884e+00, -1.51164245e+00,  3.95514697e-01,
         3.

In [7]:
np.concatenate([A1,B1])

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00],
       [ 1.00000000e+01,  1.10000000e+01,  1.20000000e+01,
         1.30000000e+01,  1.40000000e+01],
       [ 1.50000000e+01,  1.60000000e+01,  1.70000000e+01,
         1.80000000e+01,  1.90000000e+01],
       [ 2.00000000e+01,  2.10000000e+01,  2.20000000e+01,
         2.30000000e+01,  2.40000000e+01],
       [-4.67190369e-01, -1.45938013e-01,  9.12476227e-01,
        -2.18809760e+00, -1.78411034e-02],
       [ 4.69029684e-02,  4.91752075e-01,  2.10734754e+00,
        -5.36962717e-01,  4.34524116e-01],
       [ 9.13512350e-01, -6.56278142e-01, -1.31970248e+00,
         4.28307664e-02,  2.01772145e-02],
       [-3.49088291e-01,  9.47115940e-01, -1.40815374e+00,
         4.05061887e-01, -1.67177413e+00],
       [ 1.04828438e+00,  1.32936884e+00, -1.51164245e+00,
         3.95514697e-01

In [8]:
#Concatenate a panda Series
s1 = pd.Series([100,200,300], index=list('ABC'))
s2 = pd.Series([400,500], index=list('DE'))
print(s1)

A    100
B    200
C    300
dtype: int64


In [9]:
print(s2)

D    400
E    500
dtype: int64


In [10]:
pd.concat([s1,s2])

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [11]:
pd.concat([s1,s2], axis=1)

0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0

In [12]:
#Concatenation of Pandas DataFrame

df1 = pd.DataFrame(np.random.randn(12).reshape(4,3), columns=list('ABC'))
df2 = pd.DataFrame(np.arange(9).reshape(3,3), columns=list('ABD'))
print(df1)

          A         B         C
0  2.599757  1.849257 -1.502758
1 -0.723537 -0.739736  0.291607
2  0.142978 -0.023819  1.434095
3 -1.758073  0.821456 -0.703910


In [13]:
print(df2)

   A  B  D
0  0  1  2
1  3  4  5
2  6  7  8


In [14]:
pd.concat([df1, df2])

A         B         C    D
0  2.599757  1.849257 -1.502758  NaN
1 -0.723537 -0.739736  0.291607  NaN
2  0.142978 -0.023819  1.434095  NaN
3 -1.758073  0.821456 -0.703910  NaN
0  0.000000  1.000000       NaN  2.0
1  3.000000  4.000000       NaN  5.0
2  6.000000  7.000000       NaN  8.0

In [15]:
pd.concat([df1, df2], ignore_index=True)

A         B         C    D
0  2.599757  1.849257 -1.502758  NaN
1 -0.723537 -0.739736  0.291607  NaN
2  0.142978 -0.023819  1.434095  NaN
3 -1.758073  0.821456 -0.703910  NaN
4  0.000000  1.000000       NaN  2.0
5  3.000000  4.000000       NaN  5.0
6  6.000000  7.000000       NaN  8.0

In [16]:
pd.concat([df1, df2], ignore_index=True, axis=1)

0         1         2    3    4    5
0  2.599757  1.849257 -1.502758  0.0  1.0  2.0
1 -0.723537 -0.739736  0.291607  3.0  4.0  5.0
2  0.142978 -0.023819  1.434095  6.0  7.0  8.0
3 -1.758073  0.821456 -0.703910  NaN  NaN  NaN