In [1]:
#importing Numpy liberary and naming as np to use
import numpy as np

In [2]:
arr = np.arange(100, 160, 2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [3]:
#Access individual array elements
print("first element")
print(arr[0])

print("second element")
print(arr[1])

print("third element")
print(arr[2])

print("fourth element")
print(arr[3])

first element
100
second element
102
third element
104
fourth element
106


In [4]:
arr

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158])

In [5]:
#slicing of array indexes arr[start:stop:step]
arr[0:5:1]

array([100, 102, 104, 106, 108])

In [6]:
#updating array using slices
arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [7]:
#memory allocation - view vs copy
arr2 = arr[4:10]
print(arr2)
arr2[:] = 1
print(arr2)

[  0 110 112 114 116 118]
[1 1 1 1 1 1]


In [8]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [9]:
#copy() function => creating new numpy memory for array

arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


## Multidimensional Array

In [10]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Accessing Rows
print(arr2d[0])
print(arr2d[1])

[1 2 3]
[4 5 6]


In [12]:
#Accessing elements of array
print(arr2d[0][0])
print(arr2d[2][1])

1
8


In [13]:
#slicing in 2d arrays
slice1 = arr2d[0:1, 0:2]
print(slice1)
slice2 = arr2d[0:2, 0:3]
print(slice2)

[[1 2]]
[[1 2 3]
 [4 5 6]]


In [14]:
slice3 = arr2d[:2, :3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [15]:
slice4 = arr2d[1: , 2:]
print(slice4)

[[6]
 [9]]


In [16]:
#using loops to change index
arr_len = arr2d.shape
print(arr_len)
nrows = arr_len[0]

(3, 3)


In [17]:
for i in range(nrows):
    arr2d[i][0] = i
    
print(arr2d)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


## Premium Array Operations

In [18]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
B = np.arange(5, 10)
print(B)

[5 6 7 8 9]


In [20]:
C = np.arange(5,10,2)
print(C)

[5 7 9]


In [21]:
#sqrt
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [22]:
#exp()
E =  np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [23]:
#random()

F = np.random.randn(5)
print(F)


[-1.35141173  0.75279801  0.16473886 -0.39182405  1.05976432]


In [24]:
#add()
G = np.add(A, D)
print(G)

[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [25]:
#Maximum()
A = np.array([1,5,7,10])
B = np.array([0,6,8,9])

H = np.maximum(A,B)
print(H)

[ 1  6  8 10]


## Loading and Saving Arrays

In [26]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
#saving single array
np.save("saved_array", arr)

In [28]:
#loading saved array
load_Array1 = np.load('saved_array.npy')
print(load_Array1)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
#Saving Multiple Array

arr2 = np.arange(25)
arr3 = np.arange(5)

np.savez('saved_archive.npz', x=arr2, y=arr3)


In [30]:
#Loading Multiple Array
load_npz = np.load('saved_archive.npz')
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [31]:
#Saving array to text file
np.savetxt('myarray.txt', arr2, delimiter= ',')

In [32]:
#Loading array from text file
load_file = np.loadtxt('myarray.txt', delimiter=',')
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [34]:
#What is delimiter
#A delimiter is a sequence of one or more characters used to specify the 
#boundary between separate, independent regions in plain text or other 
#data streams.An example of a delimiteris the comma character, which acts 
#as a field delimiter in a sequence of comma-separated values.


In [35]:
# Following is the Types of Slicing
#1. ndarray[start:end]
#2. ndarray[start:]
#3. ndarray[:end]
#4. ndarray[start:stop:step]

In [36]:
arr = np.arange(50, 120, 2)
print(arr)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118]


In [37]:
#slicing of array indexes arr[start:stop:step]
arr[0:5:1]

array([50, 52, 54, 56, 58])

In [38]:
#slicing of array indexes arr[start:step]
arr[5:15]

array([60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [39]:
#slicing of array indexes arr[start:]
arr[15:]

array([ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118])

In [40]:
#slicing of array indexes arr[:end]
arr[:25]

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [41]:
#updating array using slices
arr[0:5] = 0
print(arr)

[  0   0   0   0   0  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118]


In [42]:
#creating 2-Dimensional array
D2array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Print 2-D array:", D2array)
print()
# Printing Element from array index 2 of 2nd row
print("2-D Elements ",D2array[1][2])
print()
#Slices of 2-D array
#We select all the elements that are in 1st through third row and in the 1st to 3rd columns
slice1 = D2array[0:2,0:2]
print(slice1)
print()
#We replace element that are in 1st through second row and in the 2nd to 3rd column with 15
D2array[:2,1:] = 15
print("After Replacement 2-D Array:\n", D2array)
print()
#We use .shape[0] to get shape of array but here create array having values(0,1,2)
arr_len = D2array.shape[0]
print("2Darray:\n", arr_len)
print()
# We are using loops to indexing and accesing elemnts of arr_len
for i in range(arr_len):
    D2array[i] = i;
print("For loop:",D2array)
print()
#one more way of accessing the rows
print(D2array[[0,1]])
print()
print(D2array[[1,0]])

Print 2-D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

2-D Elements  6

[[1 2]
 [4 5]]

After Replacement 2-D Array:
 [[ 1 15 15]
 [ 4 15 15]
 [ 7  8  9]]

2Darray:
 3

For loop: [[0 0 0]
 [1 1 1]
 [2 2 2]]

[[0 0 0]
 [1 1 1]]

[[1 1 1]
 [0 0 0]]


In [45]:
# sqrt : Use to find  the square root of elements
# exp : Perform exponent operation of maths
# random :It creates a random numbers
# addition : Perform addition of elements
# maximum : Find maximum value of all elements in array

A = np.arange(50)
print(A)

# We apply exponential and square root to all elements of A
print('EXP(A) =\n', np.exp(A))
print()

B = np.sqrt(A)
print('SQRT(A) =\n', B)
print()

#random()
C = np.random.randn(5)
print('Random(C) =\n', C)
print()

# Addition
D = np.add(A,B)
print('Addition of Array Elements(A&B) is:\n', D)
print()

#Maximum of Elements
print('Maximum value of all elements in C:', C.max())
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
EXP(A) =
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
 8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08
 4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
 2.64891221e+10 7.20048993e+10 1.95729609e+11 5.32048241e+11
 1.44625706e+12 3.93133430e+12 1.06864746e+13 2.90488497e+13
 7.89629602e+13 2.14643580e+14 5.83461743e+14 1.58601345e+15
 4.31123155e+15 1.17191424e+16 3.18559318e+16 8.65934004e+16
 2.35385267e+17 6.39843494e+17 1.73927494e+18 4.72783947e+18
 1.28516001e+19 3.49342711e+19 9.49611942e+19 2.58131289e+20
 7.01673591e+20 1.90734657e+21]

SQRT(A) =
 [0.         1.         1.41421356 1.73205081 2.         2.23

In [47]:
# Create  single arrays from 0-19
arr = np.arange(20)
print("array", arr)

#.save function saves a single array file with any name
np.save('saved_Array',arr)
#'saved_Array' is a array file name
#New file is created - saved_Array.npy

#np.load function load the previous saved file having extension .npy
new_array = np.load('saved_Array.npy')
print("Loaded File:\n",new_array)

# Multiple arrays
array1 = np.arange(20)
array2 = np.arange(45)

# .savez function use to save multidimension arrays
np.savez('saved_archive.npz',x = array1, y = array2)

load_archive = np.load('saved_archive.npz')
# Loading first  from saved file
print('load_archive[x] is:\n')
print(load_archive['x'])

# Loading second array from saved file
print('load_archive[y] is')
print(load_archive['y'])


#saving array to txtfile
#While saving array in text file we use savetxt function
np.savetxt('arrayfile.txt', array1, delimiter=',')

# delimiter is used to seprate array elements 

# loading of txt files
load_txt_file = np.loadtxt('notepadfile.txt',delimiter=',')
# loadtxt function is use to load text file array 
print("load_txt_file is")
print(load_txt_file)

array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Loaded File:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
load_archive[x] is:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
load_archive[y] is
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]


OSError: notepadfile.txt not found.