In [1]:
import numpy as np

In [8]:
#scalar array multiplication - using * operator
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = arr1 * arr1
print('Scalar array Multiplication')
print(arr2)
print()

#exponential multiplication - using ** operator
arr3 = arr1 ** 3
print('Exponential Multiplication')
print(arr3)
print()

#scalar subtraction of Array elements
arr4 = arr3 - arr1
print('Scalar Subtraction')
print(arr4)
print()

#scalar division of array elements
arr5 = 1 / arr1
print('Scalar division')
print(arr5)

Scalar array Multiplication
[[ 1  4  9]
 [25 36 49]]

Exponential Multiplication
[[  1   8  27]
 [125 216 343]]

Scalar Subtraction
[[  0   6  24]
 [120 210 336]]

Scalar division
[[1.         0.5        0.33333333]
 [0.2        0.16666667 0.14285714]]
